version: "3"
services:
   clickhouse:
     image: clickhouse/clickhouse-server
     container_name: clickhouse
     volumes:
     - ./data:/var/lib/clickhouse/
     - ./logs:/val/log/clickhouse-server/
     ports:
     - "8123:8123"
     - "9000:9000"
     - "9009:9009"

     ulimits:
      nproc: 65535
      nofile:
       soft: 262144
       hard: 262144
